import { useEffect } from "react";

function TermsConditionsContent() {
  return (
    <>
      <p className="mb-8">
        Please read these Terms and Conditions carefully before using Nova AI.
        By creating an account, accessing, or using Nova AI services, you
        declare that you have read, understood, and agree to all provisions
        contained in this document.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Definitions</h2>
      <p className="mb-4">
        <span className="font-bold">Nova AI</span> is a data-driven investment
        analysis platform based on artificial intelligence that provides
        insights, forecasting, risk modeling, scenario analysis, and
        decision-support features for investment decisions.
      </p>
      <p className="mb-4">
        <span className="font-bold">User</span> is an individual who registers
        and uses Nova AI services.
      </p>
      <p className="mb-4">
        <span className="font-bold">Insight</span> is the result of analysis
        generated by the Nova AI model based on historical data, statistics,
        machine learning, and system parameters used at the time of analysis.
      </p>
      <p className="mb-8">
        <span className="font-bold">Account</span> is the user identity used to
        access Nova AI services.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Nature of Service</h2>
      <p className="mb-4">
        Nova AI is an investment analysis and intelligence platform designed to
        help users understand opportunities, risks, and various market
        scenarios. Nova AI:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Is not an investment advisor.</li>
        <li>Is not an investment manager.</li>
        <li>Is not a broker or securities trading intermediary.</li>
        <li>Does not manage user funds.</li>
        <li>Does not execute investment transactions on behalf of the user.</li>
      </ul>
      <p className="mb-8">
        All information available on the platform is for informational and
        educational purposes.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Not Investment Advice</h2>
      <p className="mb-4">
        All insights, forecasts, risk scores, scenario projections, position
        sizing, and other information available on Nova AI are not intended as:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Investment advice.</li>
        <li>Recommendation to buy securities.</li>
        <li>Recommendation to sell securities.</li>
        <li>Solicitation to conduct specific transactions.</li>
      </ul>
      <p className="mb-8">
        Users understand that all investment decisions are entirely their own
        responsibility.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Investment Risks</h2>
      <p className="mb-4">
        Users understand that investment in the capital market involves risks
        including, but not limited to:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Loss of partial capital.</li>
        <li>Loss of entire capital.</li>
        <li>Price volatility.</li>
        <li>Liquidity risk.</li>
        <li>Market risk.</li>
        <li>Company risk.</li>
        <li>Economic and regulatory risk.</li>
      </ul>
      <p className="mb-8">
        Nova AI does not guarantee profits, specific returns, certain success
        rates, or specific investment results. Historical performance is not a
        guarantee of future results.
      </p>
      <h2 className="text-2xl font-semibold mb-2">
        System Accuracy and Limitations
      </h2>
      <p className="mb-4">
        Nova AI uses data, algorithms, statistical models, machine learning, and
        third-party information sources that may experience:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Data delays.</li>
        <li>Data errors.</li>
        <li>System disruptions.</li>
        <li>Model inaccuracies.</li>
        <li>Unexpected market changes.</li>
      </ul>
      <p className="mb-8">
        Users understand that the analysis results displayed may change at any
        time and do not always reflect actual market conditions. Nova AI does
        not guarantee the accuracy, completeness, or suitability of information
        for any particular purpose.
      </p>
      <h2 className="text-2xl font-semibold mb-2">User Account</h2>
      <p className="mb-8">
        Users are responsible for maintaining the confidentiality of their
        account and login credentials. All activity conducted through the user
        account is deemed to be conducted by the account owner. Nova AI has the
        right to suspend or terminate accounts that violate usage terms.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Fees and Subscriptions</h2>
      <p className="mb-8">
        Some Nova AI features can be accessed through paid subscription
        packages. By making a payment, the user agrees to the fees applicable at
        the time of transaction. Nova AI may change subscription prices at any
        time for the next subscription period.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Refund Policy</h2>
      <p className="mb-4">
        Unless required by applicable law, all payments made cannot be refunded.
        Refunds can only be considered if:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>System error causes duplicate payments.</li>
        <li>
          Technical issues cause the transaction not to be recorded correctly.
        </li>
      </ul>
      <p className="mb-8">
        Refund requests must be submitted no later than 7 (seven) days after the
        transaction.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Prohibited Use</h2>
      <p className="mb-4">Users are prohibited from:</p>
      <ul className="list-disc list-inside mb-4">
        <li>Reselling Nova AI access.</li>
        <li>
          Distributing, reselling, publishing, or sharing Nova AI insights with
          third parties in any form.
        </li>
        <li>Using the service for illegal activities.</li>
        <li>
          Reproducing, duplicating, copying, or reselling any part of the
          Service on our Website.
        </li>
      </ul>
      <p className="mb-8">
        Each insight is marked with a unique watermark for breach tracking.
        Violations will result in account termination without fee refund and/or
        claims for damages as per separate agreements.
      </p>
      <h2 className="text-2xl font-semibold mb-2">
        Intellectual Property Rights
      </h2>
      <p className="mb-4">All rights to:</p>
      <ul className="list-disc list-inside mb-4">
        <li>Nova AI name.</li>
        <li>Logo.</li>
        <li>Design.</li>
        <li>Algorithm.</li>
        <li>Program code.</li>
        <li>Database.</li>
        <li>Content.</li>
        <li>Analysis models.</li>
      </ul>
      <p className="mb-8">
        are the exclusive property of Nova AI and protected by applicable laws.
        Users do not obtain any ownership rights over Nova AI services.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Limitation of Liability</h2>
      <p className="mb-4">In no circumstances shall Nova AI be liable for:</p>
      <ul className="list-disc list-inside mb-4">
        <li>Investment losses.</li>
        <li>Lost profits.</li>
        <li>Lost opportunities.</li>
        <li>Indirect damages.</li>
        <li>Losses from user investment decisions.</li>
      </ul>
      <p className="mb-8">
        Nova AI's maximum liability to users, if any, is limited to the total
        subscription fees paid by the user in the last 12 months.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Force Majeure</h2>
      <p className="mb-4">
        Nova AI is not liable for delays or service failures caused by events
        beyond reasonable control, including but not limited to:
      </p>
      <ul className="list-disc list-inside mb-8">
        <li>Natural disasters.</li>
        <li>Internet disruptions.</li>
        <li>Third-party service provider disruptions.</li>
        <li>Cyberattacks.</li>
        <li>Power outages.</li>
        <li>Regulatory changes.</li>
        <li>National emergency.</li>
      </ul>
      <h2 className="text-2xl font-semibold mb-2">Changes to Terms</h2>
      <p className="mb-8">
        Nova AI has the right to change these Terms and Conditions at any time.
        Changes will be announced through the website or other official
        communication channels. Continued use of the service after changes are
        made is deemed an agreement to the updated terms.
      </p>
      <h2 className="text-2xl font-semibold mb-2">Applicable Law</h2>
      <p className="mb-8">
        These Terms and Conditions are governed by and interpreted in accordance
        with Indonesian law. Any disputes arising will be resolved first through
        deliberation. If no settlement is reached, disputes will be resolved
        through competent courts according to Indonesian law.
      </p>
      <h2 className="text-2xl font-semibold mb-2">User Consent</h2>
      <p className="mb-4">
        By creating an account or using Nova AI services, the user declares that
        they have read, understood, and agree to all contents of these Terms and
        Conditions.
      </p>
    </>
  );
}

function TermsConditions() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="border-y-1 border-gray-200/70 px-8">
      <div className="border-x-1 border-gray-200/70 py-12 px-8">
        <div className="container mx-auto px-4 py-8">
          <h1 className="text-3xl font-bold mb-4">Terms & Conditions</h1>
          <TermsConditionsContent />
        </div>
      </div>
    </div>
  );
}

export { TermsConditionsContent, TermsConditions };
