const stocksSector = {
  "BBCA.JK": "Banking",
  "BMRI.JK": "Banking",
  "BBRI.JK": "Banking",
  "BNGA.JK": "Banking",
  "BBNI.JK": "Banking",
  "BRIS.JK": "Banking",
  "BBTN.JK": "Banking",
  "BBYB.JK": "Banking",
  "BTPS.JK": "Banking",
  "BNLI.JK": "Banking",
  "NISP.JK": "Banking",
  "BDMN.JK": "Banking",
  "BSDE.JK": "Property",
  "CTRA.JK": "Property",
  "PWON.JK": "Property",
  "SMRA.JK": "Property",
  "KIJA.JK": "Property",
  "PANI.JK": "Property",
  "CBDK.JK": "Property",
  "APLN.JK": "Property",
  "ASRI.JK": "Property",
  "BKSL.JK": "Property",
  "TRIN.JK": "Property",
  "UNVR.JK": "Consumer Staples",
  "ICBP.JK": "Consumer Staples",
  "MYOR.JK": "Consumer Staples",
  "INDF.JK": "Consumer Staples",
  "ULTJ.JK": "Consumer Staples",
  "CPIN.JK": "Consumer Staples",
  "CMRY.JK": "Consumer Staples",
  "CLEO.JK": "Consumer Staples",
  "AMRT.JK": "Consumer Staples",
  "HMSP.JK": "Consumer Staples",
  "GGRM.JK": "Consumer Staples",
  "JPFA.JK": "Consumer Staples",
  "ACES.JK": "Consumer Discretionary",
  "MAPI.JK": "Consumer Discretionary",
  "ERAA.JK": "Consumer Discretionary",
  "LPPF.JK": "Consumer Discretionary",
  "ASII.JK": "Consumer Discretionary",
  "GJTL.JK": "Consumer Discretionary",
  "AUTO.JK": "Consumer Discretionary",
  "SCMA.JK": "Consumer Discretionary",
  "GOTO.JK": "Technology",
  "BUKA.JK": "Technology",
  "EMTK.JK": "Technology",
  "WIFI.JK": "Technology",
  "IRSX.JK": "Technology",
  "INET.JK": "Technology",
  "DATA.JK": "Technology",
  "KETR.JK": "Technology",
  "ADRO.JK": "Coal",
  "PTBA.JK": "Coal",
  "ITMG.JK": "Coal",
  "INDY.JK": "Coal",
  "HRUM.JK": "Coal",
  "BUMI.JK": "Coal",
  "DEWA.JK": "Coal",
  "AADI.JK": "Coal",
  "ANTM.JK": "Nickel",
  "INCO.JK": "Nickel",
  "NCKL.JK": "Nickel",
  "MBMA.JK": "Nickel",
  "NICL.JK": "Nickel",
  "DKFT.JK": "Nickel",
  "BRMS.JK": "Nickel",
  "MDKA.JK": "Gold",
  "HRTA.JK": "Gold",
  "EMAS.JK": "Gold",
  "PSAB.JK": "Gold",
  "ARCI.JK": "Gold",
  "JSMR.JK": "Infrastructure",
  "CMNP.JK": "Infrastructure",
  "IPCC.JK": "Infrastructure",
  "PBSA.JK": "Infrastructure",
  "NRCA.JK": "Infrastructure",
  "SSIA.JK": "Infrastructure",
  "TLKM.JK": "Telecom",
  "EXCL.JK": "Telecom",
  "ISAT.JK": "Telecom",
  "TBIG.JK": "Telecom",
  "CENT.JK": "Telecom",
  "KLBF.JK": "Healthcare",
  "SIDO.JK": "Healthcare",
  "MIKA.JK": "Healthcare",
  "HEAL.JK": "Healthcare",
  "SILO.JK": "Healthcare",
  "PYFA.JK": "Healthcare",
  "TSPC.JK": "Healthcare",
  "OMED.JK": "Healthcare",
  "AALI.JK": "CPO",
  "LSIP.JK": "CPO",
  "SIMP.JK": "CPO",
  "SMAR.JK": "CPO",
  "DSNG.JK": "CPO",
  "TBLA.JK": "CPO",
  "BWPT.JK": "CPO",
  "ANJT.JK": "CPO",
  "SSMS.JK": "CPO",
  "NSSS.JK": "CPO",
  "GZCO.JK": "CPO",
  "MEDC.JK": "Oil & Gas",
  "ENRG.JK": "Oil & Gas",
  "ELSA.JK": "Oil & Gas",
  "PGAS.JK": "Oil & Gas",
  "RAJA.JK": "Oil & Gas",
  "AKRA.JK": "Oil & Gas",
  "RATU.JK": "Oil & Gas",
  "PSSI.JK": "Energy Shipping",
  "TPMA.JK": "Energy Shipping",
  "SOCI.JK": "Energy Shipping",
  "WINS.JK": "Energy Shipping",
  "HAIS.JK": "Energy Shipping",
  "TCPI.JK": "Energy Shipping",
  "BULL.JK": "Energy Shipping",
  NVDA: "Technology",
  MSFT: "Technology",
  AAPL: "Technology",
  META: "Technology",
  GOOGL: "Technology",
  AMZN: "Technology",
  AMD: "Technology",
  AVGO: "Technology",
  TSM: "Technology",
  ASML: "Technology",
  ORCL: "Technology",
  CRM: "Technology",
  PLTR: "Technology",
  PANW: "Technology",
  CRWD: "Technology",
  JPM: "Financials",
  BAC: "Financials",
  GS: "Financials",
  MS: "Financials",
  BLK: "Financials",
  SCHW: "Financials",
  SPGI: "Financials",
  ICE: "Financials",
  V: "Financials",
  MA: "Financials",
  CB: "Financials",
  PGR: "Financials",
  CAT: "Industrials",
  DE: "Industrials",
  HON: "Industrials",
  GE: "Industrials",
  RTX: "Industrials",
  LMT: "Industrials",
  BA: "Industrials",
  ETN: "Industrials",
  PH: "Industrials",
  UNP: "Industrials",
  UPS: "Industrials",
  FDX: "Industrials",
  JNJ: "Healthcare",
  UNH: "Healthcare",
  LLY: "Healthcare",
  PFE: "Healthcare",
  ABDV: "Healthcare",
  MRK: "Healthcare",
  TMO: "Healthcare",
  ISRG: "Healthcare",
  ABT: "Healthcare",
  BSX: "Healthcare",
  VRTX: "Healthcare",
  AMGN: "Healthcare",
  NEE: "Utilities",
  DUK: "Utilities",
  SO: "Utilities",
  AEP: "Utilities",
  EXC: "Utilities",
  SRE: "Utilities",
  D: "Utilities",
  XEL: "Utilities",
  PEG: "Utilities",
  ED: "Utilities",
  WEC: "Utilities",
  EIX: "Utilities",
  PG: "Consumer Staples",
  KO: "Consumer Staples",
  PEP: "Consumer Staples",
  WMT: "Consumer Staples",
  COST: "Consumer Staples",
  PM: "Consumer Staples",
  MO: "Consumer Staples",
  CL: "Consumer Staples",
  MDLZ: "Consumer Staples",
  GIS: "Consumer Staples",
  TSLA: "Consumer Discretionary",
  HD: "Consumer Discretionary",
  MCD: "Consumer Discretionary",
  NKE: "Consumer Discretionary",
  SBUX: "Consumer Discretionary",
  BKNG: "Consumer Discretionary",
  RCL: "Consumer Discretionary",
  CMG: "Consumer Discretionary",
  LOW: "Consumer Discretionary",
  TJX: "Consumer Discretionary",
  ORLY: "Consumer Discretionary",
  XOM: "Energy",
  CVX: "Energy",
  COP: "Energy",
  SLB: "Energy",
  EOG: "Energy",
  MPC: "Energy",
  PSX: "Energy",
  OKE: "Energy",
  KMI: "Energy",
  LNG: "Energy",
  LIN: "Materials",
  APD: "Materials",
  NEM: "Materials",
  FCX: "Materials",
  ALB: "Materials",
  NUE: "Materials",
  STLD: "Materials",
  MOS: "Materials",
  CF: "Materials",
  SCCO: "Materials",
};

export { stocksSector };
